version: "3.7"
services:
  db:
    image: postgres:16
    container_name: task_manager_db
    env_file:
      - .env-non-dev
    command: -p 5435
    expose:
      - 5435

  task_manager_app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: task_manager_app
    command: ["/task_manager/docker/task_manager_run.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
