"""add fild file_source_url

Revision ID: 1959c5727c8e
Revises: c30cf7e8cc9a
Create Date: 2023-12-17 12:14:18.174836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1959c5727c8e"
down_revision: Union[str, None] = "c30cf7e8cc9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "file_entity", ["id"])
    op.create_unique_constraint(None, "status_entity", ["id"])
    op.add_column(
        "task_entity", sa.Column("file_source_url", sa.String(), nullable=True)
    )
    op.create_unique_constraint(None, "task_entity", ["id"])
    op.create_unique_constraint(None, "type_entity", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "type_entity", type_="unique")
    op.drop_constraint(None, "task_entity", type_="unique")
    op.drop_column("task_entity", "file_source_url")
    op.drop_constraint(None, "status_entity", type_="unique")
    op.drop_constraint(None, "file_entity", type_="unique")
    # ### end Alembic commands ###
